application: chrisalmosthex
version: 1-2
runtime: python
api_version: 1

inbound_services:
- channel_presence

handlers:
- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

- url: /tasks/.*
  script: tasks.py

- url: /.*
  script: hex.py
